### ISSUE TITLE
Link genotypes with sites

### ISSUE THREAD

**Issue by dlebauer** [terraref/reference-data#100]
Many traits in bety have a plot name but not a genotype name. These need to be updated.

For Sorghum Season 1: link cultivars and sites tables from this spreadsheet on the field 'entry' https://docs.google.com/spreadsheets/d/1s-kQc3K0h4-hfwMzKOU_zpRXN5loByIpKW8Rvw76mh0/edit#gid=796817704

then each row in traits table should have a cultivar_id that matches the 'new_cultivar_name' field. The match with site name can be partial (since some site names have 'E' or 'W' appended.

**Comment by gsrohde** [comment]
@dlebauer I have written a script to make these links.  But many of the cultivar names are not found.  I'm guessing this is only because there has been some revising of names.  For example, although there is no "PI_35038", there is "PI35038".

If I am correct that it was decided to do away with underscores in the names starting with "PI", then, rather than rewriting the CSV file, I can just hack the script to change every prefix of the form "PI_" to just "PI".  Then everything is found.  Shall I do this?

**Comment by dlebauer** [comment]
Yes please do. We decided to drop the "_"

**Comment by gsrohde** [comment]
Done.  If you think we'll do this sort of thing periodically, I'll polish up the script a bit and commit it to the Rails repository.

**Comment by rachelshekar** [comment]
@dlebauer can this be closed?

**Comment by dlebauer** [comment]
@gsrohde please post the script as a gist and link to it from this issue. If we need to do this again, we can revisit whether to clean up / generalize it.
