### ISSUE TITLE
SWIR out for service

### ISSUE THREAD

**Issue by smarshall-bmr** [terraref/reference-data#50]
Friday 8/26 the SWIR was uninstalled because its sensor thermoregulation system is failing to maintain a constant temperature. We are currently waiting for an RMA tag from Headwall before we ship it out for repairs. LemnaTec is heading this process but I'll act as a liaison and keep everyone updated as the RMA process continues. If the RMA on the VNIR is anything to go by then we will be without the SWIR for at least a month.

**Comment by smarshall-bmr** [comment]
We reinstalled the SWIR on 10/29. We're still working out some kinks with the frame grabber at the moment though.

**Comment by smarshall-bmr** [comment]
Back up and running! Turns out an internal power switch had been flipped off.

**Comment by smarshall-bmr** [comment]
I suppose I should reopen this while we are still having issues with y-axis triggered frame grabbing.

**Comment by rachelshekar** [comment]
@smarshall-bmr - has the frame grabbing issue been corrected?

**Comment by TinoDornbusch** [comment]
@rachelshekar  No the SWIR triggering is not working. Camera will be shipped back for repair again.

**Comment by rachelshekar** [comment]
FYI @dlebauer @czender @FlyingWithJerome

**Comment by smarshall-bmr** [comment]
The current plan is that the SWIR will be used in it's current state (running in untriggered mode) to capture emergence of the wheat crop before being uninstalled; likely sometime in the second or third week of January is my best guess.

**Comment by dlebauer** [comment]
@smarshall-bmr @JeffWhiteAZ 'untriggered mode' may break the hyperspectral workflow that @czender et al developed. How will the data be different? Is this a mode that we want to support in the long term, or more a short term bug that we can handle with some one-off fixes to the code. 

If it is worthwhile to support this in our workflow can you please create a new issue in which we can address these issues, point to some example data so that we can test it out? Will running in untriggered mode allow it to go faster to help with https://github.com/terraref/reference-data/issues/67?

**Comment by JeffWhiteAZ** [comment]
I would prefer to see the SWIR shipped as soon as possible. It is more useful for later stages of crop development, so with luck, we can get it back in time to use on the wheat. It would be especially useful just before harvest in order to look at moisture, cellulose and lignin.
On the un-triggered mode, my understanding is that we still have exact data on the X (north-south) position, but that the Y-location has to be inferred indirectly and may be inaccurate. That is what is pending to verify. Others should clarify.

**Comment by smarshall-bmr** [comment]
SWIR has arrived at Headwall. Updates to follow.

**Comment by smarshall-bmr** [comment]
SWIR is reinstalled and functioning as of 3/31.
